name: ⚡ Grype - Vulnerability Scan
on: 
    workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, prod-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build the container image
        run: docker build . --file Dockerfile --tag ghbuild/testimage:latest

      - name: Run Grype vulnerability scanner
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghbuild/testimage:latest"
          fail-build: false
          #severity-cutoff: high

      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
