name: ⚡ Grype - Vulnerability Scan (JSON)
on: 
    workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build the container image
        run: docker build . --file Dockerfile --tag ghbuild/testimage:latest

      - name: Run Grype vulnerability scanner
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghbuild/testimage:latest"
          fail-build: false
          severity-cutoff: critical
          output-format: json  # Set the desired output format to JSON

      # Optional step to inspect the JSON report produced
      - name: Inspect action JSON report
        run: cat ${{ steps.scan.outputs.json }}

      # Optional step to upload the JSON report as artifact
      - name: Upload Grype JSON report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-report-json
          path: ${{ steps.scan.outputs.json }}
